DROP TABLE IF EXISTS REACTIVE_EVENT;
CREATE TABLE REACTIVE_EVENT (
  EVENT_ID BIGINT NOT NULL AUTO_INCREMENT,
  TABLE_NAME VARCHAR (20) NOT NULL,
  EVENT_TYPE ENUM('INSERT', 'UPDATE', 'DELETE') NOT NULL,
  OLD_ENTITY TEXT,
  NEW_ENTITY TEXT,
  CREATED_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_ID)
);

DROP TABLE IF EXISTS REACTIVE_LISTENER;
CREATE TABLE REACTIVE_LISTENER (
  LISTENER_ID BIGINT NOT NULL AUTO_INCREMENT,
  TABLE_NAME VARCHAR (20) NOT NULL,
  WAITING_TIMEOUT_SEC BIGINT NOT NULL,
  LAST_CHECK TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  LAST_EVENT_ID BIGINT (20) NOT NULL DEFAULT 0,
  PRIMARY KEY (LISTENER_ID)
);

CREATE INDEX IDX_LISTENER_TABLE_NAME on REACTIVE_LISTENER(TABLE_NAME) using HASH;
