#!/bin/bash
# Argument = -t test -r server -p password -v

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$DIR/../../../../main/resources/scripts/utils" --source-only
. "$DIR/../../../../main/resources/scripts/setup_notifications" --source-only

TEST_DATABASE="test_dbevents"
TEST_USER="test"
TEST_SCHEMA="test"
TEST_USER_PASS="password"
TEST_TABLE="test"
TEST_STREAM="test_trigger"

start_message() {
  local answer

cat << EOF
-----------------------------------------------------------------------
This script will do the following:
* Create a new database [$TEST_DATABASE]
* Create a new user [$TEST_USER] with pasword [$TEST_USER_PASS]
* Setup the notify_with_json procedure
* Create a new schema [$TEST_SCHEMA]
* Create a new table on this schema [$TEST_TABLE]
* Create a trigger which will notify the stream [$TEST_STREAM] for every
  update in the table [$TEST_TABLE].

You have selected the following params for connection:
SERVER: $SERVER:$PORT
USERNAME: $USERNAME
DATABASE: $DATABASE (Used only for initial login)
-----------------------------------------------------------------------
EOF
  echo -n "Do you want to proceed(y/n)? [Default is y]: "
  read answer

  if [[ $answer == "n" ]]; then
    exit 0
  fi
}

readConnectionParams "$@"
if [ $? -ne 0 ]; then
  usage_notifications
  exit 1
fi

start_message

echo "Creating test database [$TEST_DATABASE] and user [$TEST_USER]/[$TEST_USER_PASS]"
psql -h $SERVER -p $PORT -U $USERNAME -d $DATABASE -f "$DIR/create-db-and-user.sql"
verifyLastCommand "Failed to create database and/or user"

echo "Starting rest of scripts with test user"
USERNAME=$TEST_USER
DATABASE=$TEST_DATABASE

echo "Creating schema and tables in the test database"
psql -h $SERVER -p $PORT -U $USERNAME -d $DATABASE -f "$DIR/init-db.sql"
verifyLastCommand "Failed to create schema or tables in the test database"

echo "Setting up triggers"
setup_notifications $SERVER $PORT $DATABASE $USERNAME $TEST_TABLE $TEST_STREAM

echo "SUCCESS!"
